CREATE TABLE campuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE classrooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id BIGINT NOT NULL REFERENCES campuses(id),
    name VARCHAR(100) NOT NULL,
    CONSTRAINT uq_classroom_campus_name UNIQUE (campus_id, name),
    CONSTRAINT uq_classroom_id_campus UNIQUE (id, campus_id)
);

CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL CHECK (role IN ('STUDENT', 'PROFESSOR', 'ADMIN'))
);

CREATE TABLE enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL UNIQUE REFERENCES app_users(id),
    campus_id BIGINT NOT NULL REFERENCES campuses(id),
    classroom_id BIGINT NOT NULL,
    CONSTRAINT fk_enrollment_classroom_campus
        FOREIGN KEY (classroom_id, campus_id) REFERENCES classrooms(id, campus_id)
);

CREATE TABLE professor_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id BIGINT NOT NULL REFERENCES app_users(id),
    classroom_id BIGINT NOT NULL REFERENCES classrooms(id),
    CONSTRAINT uq_professor_classroom UNIQUE (professor_id, classroom_id)
);
