CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL REFERENCES app_users(id),
    campus_id BIGINT NOT NULL REFERENCES campuses(id),
    classroom_id BIGINT NOT NULL,
    category VARCHAR(100) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('OPEN')),
    source VARCHAR(20) NOT NULL CHECK (source IN ('WEB')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_question_classroom_campus
        FOREIGN KEY (classroom_id, campus_id) REFERENCES classrooms(id, campus_id)
);

CREATE INDEX idx_question_author_created_at ON questions(author_id, created_at DESC);
