ALTER TABLE questions DROP CONSTRAINT IF EXISTS questions_status_check;
ALTER TABLE questions DROP CONSTRAINT IF EXISTS ck_questions_status;
ALTER TABLE questions DROP CONSTRAINT IF EXISTS CONSTRAINT_3BDD5;

ALTER TABLE questions
    ADD CONSTRAINT ck_questions_status CHECK (status IN ('OPEN', 'ANSWERED'));

CREATE TABLE answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL UNIQUE REFERENCES questions(id),
    professor_id BIGINT NOT NULL REFERENCES app_users(id),
    content TEXT NOT NULL,
    visibility VARCHAR(20) NOT NULL CHECK (visibility IN ('PRIVATE', 'CLASS', 'CAMPUS', 'GLOBAL')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
