CREATE TABLE slack_user_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES app_users(id),
    slack_user_id VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE slack_channel_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type VARCHAR(30) NOT NULL,
    scope_id BIGINT,
    slack_channel_id VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT uq_slack_channel_scope UNIQUE (scope_type, scope_id)
);
