CREATE TABLE enrollment_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    previous_campus_id BIGINT,
    previous_classroom_id BIGINT,
    new_campus_id BIGINT NOT NULL,
    new_classroom_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_enrollment_audit_student_created_at
    ON enrollment_audit_logs(student_id, created_at DESC);
